/* include/opcodes.h - GunBound wire opcodes.
 *
 * GENERATED by tools/gen_opcodes_h.py from the server repo's
 * Sources/GunBoundProtocol/Opcode.swift - do not hand-edit; re-run the
 * generator after changing the Swift enum so both repos stay in step.
 *
 * Macro names are the Swift case names in UPPER_SNAKE with a GB_OP_
 * prefix; where the Swift source carries the original SVC_* name as a
 * trailing comment it is repeated here.  Values are the 16-bit opcode
 * as the client compares it (`opcode == 0x3020`, `case 0x4412:`).
 * See CONSTANTS.md section 3/4 and PROTOCOL.md for what each one does.
 */
#ifndef GB_OPCODES_H
#define GB_OPCODES_H


/* --- Connection --- */
#define GB_OP_KEEP_ALIVE                             0x0000

/* --- Authentication --- */
#define GB_OP_NONCE_REQUEST                          0x1000
#define GB_OP_NONCE_RESPONSE                         0x1001
#define GB_OP_AUTHENTICATION_REQUEST                 0x1010
#define GB_OP_AUTHENTICATION_RESPONSE                0x1012
#define GB_OP_SESSION_HANDOFF_NOTIFICATION           0x101F
#define GB_OP_USER_REQUEST                           0x1020  /* SVC_USER_ID */
#define GB_OP_USER_RESPONSE                          0x1021
#define GB_OP_USER_NICKNAME_REQUEST                  0x1022  /* SVC_USER_NICK */

/* --- Server Directory --- */
#define GB_OP_SERVER_DIRECTORY_REQUEST               0x1100
#define GB_OP_SERVER_DIRECTORY_RESPONSE              0x1102

/* --- Currency Updates --- */
#define GB_OP_CASH_UPDATE_NOTIFICATION               0x1032
#define GB_OP_CASH_UPDATE_REQUEST                    0x6100
#define GB_OP_GOLD_UPDATE_REQUEST                    0x6104
#define GB_OP_GOLD_UPDATE_RESPONSE                   0x6105

/* --- Channel --- */
#define GB_OP_JOIN_CHANNEL_REQUEST                   0x2000  /* SVC_CHANNEL_JOIN */
#define GB_OP_JOIN_CHANNEL_RESPONSE                  0x2001
#define GB_OP_JOIN_CHANNEL_NOTIFICATION              0x200E

/* --- Room List --- */
#define GB_OP_ROOM_LIST_REQUEST                      0x2100  /* SVC_ROOM_SORTED_LIST */
#define GB_OP_ROOM_SPECIFIC_LIST                     0x2101  /* SVC_ROOM_SPECIFIC_LIST */
#define GB_OP_ROOM_LIST_RESPONSE                     0x2103
#define GB_OP_ROOM_DETAIL_REQUEST                    0x2104  /* SVC_ROOM_DETAIL */
#define GB_OP_ROOM_DETAIL_RESPONSE                   0x2105

/* --- Buddy List --- */
#define GB_OP_BUDDY_LIST_REQUEST                     0x2200
#define GB_OP_BUDDY_LIST_RESPONSE                    0x2201
#define GB_OP_BUDDY_ADD_COMMAND                      0x2202
#define GB_OP_BUDDY_REMOVE_COMMAND                   0x2203
#define GB_OP_BUDDY_LIST_NOTIFICATION                0x2204

/* --- Room Management --- */
#define GB_OP_JOIN_ROOM_REQUEST                      0x2110  /* SVC_ROOM_JOIN */
#define GB_OP_JOIN_ROOM_RESPONSE                     0x2111
#define GB_OP_JOIN_ROOM_NOTIFICATION                 0x3010
#define GB_OP_JOIN_ROOM_NOTIFICATION_SELF            0x21F5
#define GB_OP_ROOM_SELF_DISPLAY_UPDATE_NOTIFICATION  0x21F0
#define GB_OP_ROOM_PLAYER_LEFT_NOTIFICATION          0x21F1
#define GB_OP_ROOM_PLAYER_DISPLAY_UPDATE_NOTIFICATION 0x21F2
#define GB_OP_ROOM_PLAYER_FLAG_UPDATE_NOTIFICATION   0x21F3
#define GB_OP_ROOM_PLAYER_VALUE_UPDATE_NOTIFICATION  0x21F4
#define GB_OP_ROOM_PLAYER_STATUS_UPDATE_NOTIFICATION 0x21F6
#define GB_OP_ROOM_PLAYER_MODE_UPDATE_NOTIFICATION   0x21F7
#define GB_OP_CHANNEL_CHAT_COMMAND                   0x2010  /* SVC_CHANNEL_CHAT */
#define GB_OP_CHANNEL_CHAT_BROADCAST                 0x201F

/* --- Room Creation --- */
#define GB_OP_CREATE_ROOM_REQUEST                    0x2120  /* SVC_ROOM_CREATE */
#define GB_OP_CREATE_ROOM_RESPONSE                   0x2121

/* --- Room Commands --- */
#define GB_OP_ROOM_CHANGE_STAGE_COMMAND              0x3100  /* SVC_ROOM_CHANGE_STAGE */
#define GB_OP_ROOM_CHANGE_OPTION_COMMAND             0x3101  /* SVC_ROOM_CHANGE_OPTION */
#define GB_OP_ROOM_CHANGE_USE_ITEM_COMMAND           0x3102  /* SVC_ROOM_CHANGE_USEITEM */
#define GB_OP_ROOM_CHANGE_CAPACITY_COMMAND           0x3103  /* SVC_ROOM_CHANGE_MAXMEN */
#define GB_OP_ROOM_SET_TITLE_COMMAND                 0x3104  /* SVC_ROOM_CHANGE_TITLE */
#define GB_OP_ROOM_UPDATE_NOTIFICATION               0x3105

/* --- Room Player Actions --- */
#define GB_OP_ROOM_SELECT_TEAM_REQUEST               0x3210  /* SVC_ROOM_SELECT_TEAM */
#define GB_OP_ROOM_SELECT_TEAM_RESPONSE              0x3211
#define GB_OP_ROOM_KICK_USER_REQUEST                 0x3150  /* SVC_ROOM_KICK_USER */
#define GB_OP_ROOM_SELECT_TANK_REQUEST               0x3200  /* SVC_ROOM_SELECT_TANK */
#define GB_OP_ROOM_SELECT_TANK_RESPONSE              0x3201
#define GB_OP_ROOM_USER_READY_REQUEST                0x3230  /* SVC_ROOM_USER_READY */
#define GB_OP_ROOM_USER_READY_RESPONSE               0x3231
#define GB_OP_ROOM_RETURN_RESULT_REQUEST             0x3232  /* SVC_ROOM_RETURN_RESULT */
#define GB_OP_ROOM_RETURN_RESULT_RESPONSE            0x3233
#define GB_OP_USER_QUIT_NOTIFICATION                 0x3020
#define GB_OP_ROOM_CHANGE_TEAM_NOTIFICATION          0x3151
#define GB_OP_HOST_MIGRATION_NOTIFICATION            0x3400
#define GB_OP_ROOM_READY_CONFIRMATION_NOTIFICATION   0x3431

/* --- Gameplay --- */
#define GB_OP_START_GAME_COMMAND                     0x3430  /* SVC_START_GAME */
#define GB_OP_START_GAME_NOTIFICATION                0x3432
#define GB_OP_CLOSE                                  0x3FFF
#define GB_OP_GAME_DROP_USER_COMMAND                 0x4000  /* SVC_PLAY_DROP_USER */
#define GB_OP_END_GAME_JEWEL_COMMAND                 0x4200  /* SVC_PLAY_END_JEWEL */
#define GB_OP_USER_DEAD_REQUEST                      0x4100
#define GB_OP_USER_DEAD_RESPONSE                     0x4101  /* SVC_PLAY_USER_DEAD */
#define GB_OP_PLAY_RESURRECT                         0x4104  /* SVC_PLAY_RESURRECT */
#define GB_OP_PLAY_RESULT_COMMAND                    0x4412  /* SVC_PLAY_RESULT */
#define GB_OP_PLAY_RESULT_NOTIFICATION               0x4413
#define GB_OP_PLAYER_DEAD_NOTIFICATION               0x4102

/* --- Server/Admin Commands --- */
#define GB_OP_POLICE_ACCUSE                          0x5000  /* SVC_POLICE_ACCUSE */
#define GB_OP_USER_INFO                              0x5002  /* SVC_USER_INFO */
#define GB_OP_BCM                                    0x5010  /* SVC_BCM */
#define GB_OP_CLIENT_COMMAND                         0x5100  /* SVC_COMMAND */
#define GB_OP_CLIENT_PRINT_NOTIFICATION              0x5101
#define GB_OP_CLIENT_COMMAND_STATUS                  0x5110  /* SVC_CMD_STATUS */
#define GB_OP_CLIENT_COMMAND_MOTD                    0x5112  /* SVC_CMD_MOTD */
#define GB_OP_CLIENT_COMMAND_BCM                     0x5114  /* SVC_CMD_BCM */
#define GB_OP_CLIENT_COMMAND_SET_VERSION             0x5116  /* SVC_CMD_SETVERSION */
#define GB_OP_CLIENT_COMMAND_GRADE_LIMIT             0x5120  /* SVC_CMD_GRADELIMIT */
#define GB_OP_CLIENT_COMMAND_GUILD_MARK_LIMIT        0x5122  /* SVC_CMD_GUILDLIMIT */
#define GB_OP_CLIENT_COMMAND_FUNCTION_RESTRICT       0x5124  /* SVC_CMD_FUNCTION_RESTRICT */
#define GB_OP_CLIENT_COMMAND_ALLOWED_GUILD           0x5126  /* SVC_CMD_SET_ALLOWEDGUILD */
#define GB_OP_CLIENT_SET_EVENT_ACT_PROB              0x5128  /* SVC_CMD_SET_EVENTACTPROB */
#define GB_OP_CLIENT_SET_PASSABLE_AUTHORITY          0x512A  /* SVC_CMD_SET_PASSABLE_AUTH */
#define GB_OP_GAME_END_NOTIFICATION                  0x4410
#define GB_OP_TUNNEL                                 0x4500  /* SVC_TUNNEL */
#define GB_OP_TUNNEL_FORWARD                         0x4501

/* --- Shop/Avatar --- */
#define GB_OP_GET_AVATAR_REQUEST                     0x6000  /* SVC_PROP_GET */
#define GB_OP_GET_AVATAR_RESPONSE                    0x6001
#define GB_OP_AVATAR_INVENTORY_RESPONSE              0x6002
#define GB_OP_SET_AVATAR_REQUEST                     0x6004  /* SVC_PROP_SET */
#define GB_OP_SET_AVATAR_RESPONSE                    0x6005
#define GB_OP_BUY_GOLD_REQUEST                       0x6010  /* SVC_PROP_BUY */
#define GB_OP_BUY_CASH_REQUEST                       0x6011  /* SVC_PROP_BUY_PP */
#define GB_OP_BUY_RESPONSE                           0x6017
#define GB_OP_SELL_REQUEST                           0x6020  /* SVC_PROP_SELL */
#define GB_OP_SELL_GIVEN                             0x6021  /* SVC_PROP_SELL_GIVEN */
#define GB_OP_SELL_RESPONSE                          0x6027
#define GB_OP_GIFT_REQUEST                           0x6030  /* SVC_PROP_GIFT */
#define GB_OP_GIFT_GIVEN                             0x6031  /* SVC_PROP_GIFT_GIVEN */
#define GB_OP_BUY_GOLD_GIFT_REQUEST                  0x6032  /* SVC_PROP_GIFT_BUY */
#define GB_OP_BUY_CASH_GIFT_REQUEST                  0x6033  /* SVC_PROP_GIFT_BUY_PP */
#define GB_OP_GIFT_RESPONSE                          0x6037
#define GB_OP_USER_CENTER_LOCATION_REQUEST           0xCF02  /* RCTS_USER_LOCATION */
#define GB_OP_USER_CENTER_RECORD_REQUEST             0xC103
#define GB_OP_UNKNOWN                                0x9999

/* --- Supporting Types --- */


/* --- Channel-2 battle ACTION codes (ProcessBattleAction, +0x02 of the ---
 * --- 33-byte action header).  Not part of the server's Opcode enum.  --- */
#define GB_ACT_NOTIFICATION_TOAST                    0x0003
#define GB_ACT_PLAYER_INFO_SYNC                      0x8000
#define GB_ACT_CHAT_BUFFER_UPDATE                    0x8003
#define GB_ACT_UI_REFRESH                            0x8004
#define GB_ACT_FIELD_RELAY                           0x8005
#define GB_ACT_FIRE_FEEDBACK_SOUND                   0x8006
#define GB_ACT_MOBILE_MODEL_SYNC                     0x8100
#define GB_ACT_MAP_SELECTION_SYNC                    0x8101
#define GB_ACT_ALL_PLAYERS_READY                     0x8102
#define GB_ACT_SHOW_RESULT_CONFIRM                   0x8104
#define GB_ACT_KICK_FROM_ROOM                        0x8200
#define GB_ACT_MOBILE_MODEL_SYNC_ALT                 0x8400
#define GB_ACT_AIM_RELAY                             0x8402  /* angle+power, +0x243/+0x2cc */
#define GB_ACT_FIRE                                  0x8403  /* "ifire"; 8 server-resolved u16 */
#define GB_ACT_HIT_LOG                               0x8404
#define GB_ACT_WEAPON_SELECT_SOUND                   0x8405
#define GB_ACT_AIM_RELAY_ALT                         0x8406
#define GB_ACT_CHECKSUM_KEEPALIVE                    0x8407
#define GB_ACT_PLAYER_SPAWN                          0x8408
#define GB_ACT_POSITION_RELAY                        0x8500  /* also a replay-event code */
#define GB_ACT_GAME_START_COUNTDOWN                  0x9002  /* countdown := 0x31 */
#define GB_ACT_TURN_START                            0xC300  /* BeginNewTurn */
#define GB_ACT_TURN_SETUP                            0xC301  /* turn-timer + wind/spawn write */
#define GB_ACT_TURN_PHASE                            0xC303
#define GB_ACT_MOVEMENT                              0xC304  /* 4-bit dir | 0x10 running */
#define GB_ACT_TURN_TIMEOUT                          0xC305
#define GB_ACT_AIM_CONFIRM                           0xC306
#define GB_ACT_WIND_UPDATE                           0xC308
#define GB_ACT_SCHED_CHECKPOINT                      0xC400  /* no-op */
#define GB_ACT_TIMEOUT_WEAPON_SELECT                 0xC401
#define GB_ACT_FIRE_COMMITTED                        0xC409
#define GB_ACT_TIMEOUT_BOOKKEEPING                   0xC40B  /* all 8 slots */
#define GB_ACT_PERIODIC_STATUS                       0xC801
#define GB_ACT_QUIT                                  0xF008
#define GB_ACT_CHANGE_MOBILE                         0xF009  /* ChangePlayerMobile */
#define GB_ACT_PLAYER_FIELD_QUERY                    0xF00A
#define GB_ACT_TERRAIN_DEFORM                        0xF00B  /* crater frame swap */
/* Seen but still marked tentative in CONSTANTS.md, so left unnamed:
 *   0x0001 (ready-room player-data load), 0x4001-0x4006 (in-battle chat /
 *   status relays; 0x4002 is proximity chat), 0xC40A (final position sync).
 * Confirmed never implemented (default no-op): 0xC302, 0xC307, 0xC309,
 *   0xC402-0xC408. */

#endif /* GB_OPCODES_H */
