#!/usr/bin/env python3
"""Independent second-opinion decompile of the WinMain->server-list
function set (see gen_diff_report.py's FUNCS) using angr's VEX-based
decompiler, as a cross-check against Ghidra's decompiler when reading a
function's true logic.

angr and Ghidra use different IR/structuring engines (VEX+AIL vs.
p-code+Ghidra's own structuring), so they occasionally disagree about
things like loop shape or register/arg recovery - when they agree, that's
useful confirmation; when they disagree, that's a flag to look closer at
the raw asm rather than trust either decompiler blindly.

Usage:
    tools/.venv-angr/bin/python3 tools/angr_decompile.py [outdir]

Requires: tools/.venv-angr (pip install angr), orig/GunBound.gme.
Output: one .c file per function in outdir (default tools/angr_ref/),
named <symbol>_<va>.c, containing angr's pseudocode plus a header comment.
"""
import os
import sys
import time

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(REPO, "tools"))
import gen_diff_report as gdr  # reuse the FUNCS list (file, VA hex, symbol hint)

GME = os.path.join(REPO, "orig", "GunBound.gme")


def main():
    outdir = sys.argv[1] if len(sys.argv) > 1 else os.path.join(REPO, "tools", "angr_ref")
    os.makedirs(outdir, exist_ok=True)

    import angr
    import logging
    logging.getLogger("angr").setLevel(logging.ERROR)

    print(f"Loading {GME} ...")
    proj = angr.Project(GME, auto_load_libs=False, load_options={"main_opts": {"base_addr": 0x400000}})

    print("Building CFG (CFGFast) ...")
    t0 = time.time()
    cfg = proj.analyses.CFGFast(normalize=True, data_references=True)
    print(f"CFG done in {time.time()-t0:.1f}s, {len(cfg.kb.functions)} functions found")

    ok, fail = 0, 0
    for src_rel, va_hex, hint in gdr.FUNCS:
        addr = int(va_hex, 16)
        out_name = f"{hint.lstrip('_@')}_{va_hex}.c"
        out_path = os.path.join(outdir, out_name)
        func = cfg.kb.functions.get(addr)
        if func is None:
            print(f"SKIP {hint} @ {va_hex}: no function recovered at this address by CFGFast")
            fail += 1
            continue
        try:
            dec = proj.analyses.Decompiler(func, cfg=cfg.model)
            text = dec.codegen.text if dec.codegen else None
        except Exception as e:
            print(f"FAIL {hint} @ {va_hex}: {e}")
            fail += 1
            continue
        if not text:
            print(f"FAIL {hint} @ {va_hex}: decompiler produced no output")
            fail += 1
            continue
        with open(out_path, "w") as f:
            f.write(f"// angr decompile - {hint} @ 0x{va_hex}\n")
            f.write(f"// cross-reference for {src_rel} (Ghidra decompile / hand-ported C)\n")
            f.write(f"// generated by tools/angr_decompile.py\n\n")
            f.write(text)
        print(f"OK   {hint} @ {va_hex} -> {out_name}")
        ok += 1

    print(f"\n{ok} decompiled, {fail} failed/skipped, output in {outdir}")


if __name__ == "__main__":
    main()
