#!/usr/bin/env python3
"""Generate no-op stub .c files for every symbol still unresolved in the
MSVC link attempt, so the bring-up exe never jumps to a zeroed /FORCE
call target. Reads link.log, writes bringup_stubs_*.c next to it.

Decorated-name classes handled:
  @name@N   -> int __fastcall name(int a1..a{N/4})      { return 0; }
  _name@N   -> int __stdcall  name(int a1..a{N/4})      { return 0; }
  _name     -> int            name()                    { return 0; }

Every stub returns 0: pointer-returning callees are null-checked at the
raw-port call sites, so 0 degrades to "feature absent" instead of a
crash. One file per (convention, argbytes) class because the same
identifier can be unresolved under several decorations (e.g.
@PanelManager_BringToFront@0 AND @4) and each spelling needs its own TU.

MANUAL_STUBS below are the exceptions to that "return 0 is safe" rule:
symbols whose raw-port callers do NOT null-check the result, so a 0
return is itself the crash. Each entry supplies a hand-written body that
satisfies the invariant its callers actually rely on. They are emitted
to bringup_stubs_manual.c (same bringup_stubs_* glob the link script
already cleans, compiles and links) and excluded from the auto groups.

Usage: gen_bringup_stubs.py <link.log> <outdir>
"""
import re
import sys
from collections import defaultdict

log_path, outdir = sys.argv[1], sys.argv[2]

# Decorated symbol -> hand-written definition. See the module docstring.
MANUAL_STUBS = {}

syms = set()
with open(log_path, errors="replace") as f:
    for m in re.finditer(r"unresolved external symbol (\S+)", f.read()):
        s = m.group(1).rstrip("\r")
        if s.startswith('"'):  # C++-mangled: none expected; fail loudly
            sys.exit(f"C++-mangled unresolved remains, no stub possible: {s}")
        syms.add(s)

manual = sorted(syms & set(MANUAL_STUBS))
unused = sorted(set(MANUAL_STUBS) - syms)
if unused:
    # A manual stub that is no longer unresolved means its real object is back
    # in the link; leaving the override in would be a duplicate definition.
    sys.exit(f"MANUAL_STUBS entries no longer unresolved, remove them: {unused}")

groups = defaultdict(list)  # (conv, argbytes) -> [identifier]
for s in sorted(syms - set(MANUAL_STUBS)):
    if s.startswith("@"):                       # fastcall @name@N
        name, n = s[1:].rsplit("@", 1)
        groups[("__fastcall", int(n))].append(name)
    elif "@" in s:                              # stdcall _name@N
        name, n = s[1:].rsplit("@", 1)
        groups[("__stdcall", int(n))].append(name)
    else:                                       # cdecl _name
        groups[("", 0)].append(s[1:])

total = 0
if manual:
    with open(f"{outdir}/bringup_stubs_manual.c", "w") as f:
        f.write("/* GENERATED by gen_bringup_stubs.py from its MANUAL_STUBS table.\n"
                " * Hand-written bodies - edit them in gen_bringup_stubs.py, not here.\n"
                " * These callees' results are NOT null-checked by their raw-port\n"
                " * callers, so the usual `return 0` stub would itself be the crash. */\n")
        for s in manual:
            f.write(MANUAL_STUBS[s])
    total += len(manual)
    print(f"bringup_stubs_manual.c: {len(manual)} hand-written stubs ({', '.join(manual)})")
for (conv, n), names in sorted(groups.items()):
    tag = {"__fastcall": f"fc{n}", "__stdcall": f"std{n}"}.get(conv, "cdecl")
    args = ", ".join(f"int a{i+1}" for i in range(n // 4)) if conv else ""
    with open(f"{outdir}/bringup_stubs_{tag}.c", "w") as f:
        f.write(f"/* AUTO-GENERATED by gen_bringup_stubs.py - do not edit.\n"
                f" * No-op bring-up stubs, {conv or 'cdecl'}"
                f"{f' {n} arg bytes' if conv else ''}. */\n")
        for name in names:
            f.write(f"int {conv + ' ' if conv else ''}{name}({args}) {{ return 0; }}\n")
    total += len(names)
    print(f"bringup_stubs_{tag}.c: {len(names)} stubs")
print(f"total: {total} stubs for {len(syms)} unresolved symbols")
